### ISSUE TITLE
linux-drm-intel-nightly: install: does it use the correct kernel?!

### ISSUE THREAD

**Issue by blueyed** [WarheadsSE/PKGs#10]
I came across https://github.com/WarheadsSE/PKGs/blob/master/linux-drm-intel-nightly/linux-drm-intel-nightly.install#L4-L12, and it looks like while the PKGBUILD would use `pkgbase=linux-drm-intel-nightly` for the kernel name (or derivations therefore), the install script would just use `linux` always?!

I have not tried to install it actually (yet).

**Comment by WarheadsSE** [comment]
This is actually replaced with the correct value at https://github.com/WarheadsSE/PKGs/blob/master/linux-drm-intel-nightly/PKGBUILD#L101

**Comment by blueyed** [comment]
Thanks, closing!

Will try this kernel to see if it fixes issues I am seeing on a lenovo x250 with regard to a big screen.

I came across https://www.reddit.com/r/archlinux/comments/4cojj9/it_is_probably_time_to_ditch_xf86videointel/ and am therefore currently not using the xorg driver, which appears to help in this regard already.

Thanks for maintaining this package!
