### ISSUE TITLE
MD5dums and distccmon

### ISSUE THREAD

**Issue by gearhead** [WarheadsSE/PKGs#12]
Md5sums had to be revised for the arm package.  Also, is there a way to use distccmon-text with this package?

**Comment by WarheadsSE** [comment]
The checksums have all been updated. I will have to look into `disctccmon-text`

**Comment by WarheadsSE** [comment]
https://wiki.archlinux.org/index.php/Distcc#Monitoring_progress

You can watch on the slaves with `journalctl`,  as documented, and you _should_ be able to monitor with `distccmon-text` on the ARM device running the job.
