### ISSUE TITLE
distcc-alarm: PKGBUILD has outdated md5s

### ISSUE THREAD

**Issue by gyscos** [WarheadsSE/PKGs#13]
[distccd-alarm](https://github.com/WarheadsSE/PKGs/tree/master/distccd-alarm) seems to have outdated md5sumds in the PKGBUILD.

```
 md5sum x-tools*
13129e63d582c91bda6b76a23d7393b9  x-tools.tar.xz
a3ce73b9790056538dd77608dfd8b0f1  x-tools6h.tar.xz
162b43fdc0f2a3421c25aa45af77c916  x-tools7h.tar.xz
87a638a8409692b5ace07bd632ac20e9  x-tools8.tar.xz
```

From PKGBUILD:
```
a3a3f6f2866a06687e83677a74a9e75d # x-tools.tar.xz
1e3725360bc5600cb37e7cfdf88bc9e8 # x-tools6h.tar.xz
988ca5511f6ae080b8973ae7a42ded56 # x-tools7h.tar.xz
c459576a7145c421a1e9b5cfbbbbfd9a # x-tools8.tar.xz
```

The checksums on https://archlinuxarm.org/wiki/Distcc_Cross-Compiling also seem outdated.

**Comment by gyscos** [comment]
Probably related: the latest `x-tools8.tar.xz` contains a `x-tools8/aarch64-unknown-linux-gnueabi` directory, instead of the `arm-unknown-linux-gnueabihf` mentioned in `distccd-armv8.conf`.

**Comment by WarheadsSE** [comment]
GCC 7 and friends recently rolled through, so this is the culprit.

**Comment by WarheadsSE** [comment]
@gyscos Would you like to create a PR, or wait for me to complete the work?
