### ISSUE TITLE
distcc-alarm: PKGBUILD has outdated md5s

### ISSUE THREAD

**Issue by videda** [WarheadsSE/PKGs#15]
The x-tools* md5sums in the distcc-alarm PKBUILD seem outdated.

```
md5sums=('1e289a79b68c6f1d4403ca767b426f5f'
         'c4619cc2542a6bf0df5005fcb2334af7'
         '930e6469480395e028b4eb4000659fde'
        'd1a7cb480f1090ce6a5a370cd5cec4cd'
```
The ones at https://archlinuxarm.org/wiki/Distcc_Cross-Compiling seem right:

    ARMv5te soft (1ade1ced844961a39e1e539fb04c1d65)
    ARMv6l hard (bfe68188dae1512690d9981ff0ee7460)
    ARMv7l hard (2ae08024566bd62249d4a83ee8d90124)
    ARMv8 (79c3880c29bc8994d2136af553ca4d6d)

Thanks

**Comment by pswiatki** [comment]
Shouldn't md5sums come from the same location as x-tools themselves? There should be an easy way to compare locally calculated md5 with the one provided by archlinuxarm, right?
